// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apishop

// CardView は card service の CardDefinition レスポンスを shop 側で必要な範囲に絞った projection。
type CardView struct {
	CardID      string `json:"card_id"`
	CardName    string `json:"card_name"`
	Faction     string `json:"faction"`
	CardType    string `json:"card_type"`
	Restriction string `json:"restriction"`
	IsActive    bool   `json:"is_active"`
}

