package apishop

import "time"

// faction 購入イベントの topic 名。
const TopicFactionPurchased = "faction-purchased"

// FactionPurchasedEvent の EventType 値。
const EventTypeFactionPurchased = "faction_purchased"

// FactionPurchasedEvent is published by shop when a player purchases a faction
// (post-onboarding, incremental ownership). Subscribers:
//
//   - account: INSERTs account.player_factions (does NOT update selected_faction).
//   - card:    grants faction-specific cards (no Neutral, initial pack was already
//              granted at onboarding time via player-onboarded).
//   - gateway: pushes a WS `faction_purchase_complete` message.
//
// Idempotency: subscribers MUST dedupe on EventID via their
// processed_events table. See ADR-022 for the decomposition rationale.
type FactionPurchasedEvent struct {
	// EventType is always EventTypeFactionPurchased.
	EventType string `json:"event_type"`
	// EventID is a UUIDv4 generated by shop. Idempotency key.
	EventID string `json:"event_id"`
	// Timestamp is the publisher's wall clock at enqueue time.
	Timestamp time.Time `json:"timestamp"`
	// PlayerID is the target of the faction ownership grant.
	PlayerID string `json:"player_id"`
	// Faction is one of SelectableFactions (SHE / Tenki / Sugar / Tuners).
	Faction string `json:"faction"`
}
