// Package apishop provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apishop

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Platform.
const (
	PlatformAndroid Platform = "android"
	PlatformIos     Platform = "ios"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case PlatformAndroid:
		return true
	case PlatformIos:
		return true
	default:
		return false
	}
}

// Defines values for ProductType.
const (
	ProductTypeCardPack     ProductType = "card_pack"
	ProductTypeCosmetic     ProductType = "cosmetic"
	ProductTypeFactionSet   ProductType = "faction_set"
	ProductTypeSubscription ProductType = "subscription"
)

// Valid indicates whether the value is a known member of the ProductType enum.
func (e ProductType) Valid() bool {
	switch e {
	case ProductTypeCardPack:
		return true
	case ProductTypeCosmetic:
		return true
	case ProductTypeFactionSet:
		return true
	case ProductTypeSubscription:
		return true
	default:
		return false
	}
}

// AppleNotificationPayload defines model for AppleNotificationPayload.
type AppleNotificationPayload struct {
	// SignedPayload Apple JWS 署名済みペイロード本体。
	SignedPayload string `json:"signedPayload"`
}

// GoogleRTDNMessage defines model for GoogleRTDNMessage.
type GoogleRTDNMessage struct {
	Message GoogleRTDNMessageBody `json:"message"`
}

// GoogleRTDNMessageBody defines model for GoogleRTDNMessageBody.
type GoogleRTDNMessageBody struct {
	// Data base64 エンコードされた DeveloperNotification 本体。
	Data string `json:"data"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Platform クライアント実行プラットフォーム。
type Platform string

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Products []ProductResponse `json:"products"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	// Content 商品 type ごとに固有の構造を持つ JSON オブジェクト。type=faction_set なら `{faction}`, type=cosmetic なら `{item_type, item_no}`, type=subscription なら `{}`、type=card_pack なら `{card_pack_id}`。
	Content     map[string]interface{} `json:"content"`
	Description *string                `json:"description,omitempty"`
	ImageURL    *string                `json:"image_url,omitempty"`
	IsActive    bool                   `json:"is_active"`
	IsOwned     bool                   `json:"is_owned"`
	Name        string                 `json:"name"`
	Price       int64                  `json:"price"`
	ProductID   string                 `json:"product_id"`

	// Type 商品種別の discriminator。
	Type ProductType `json:"type"`
}

// ProductType 商品種別の discriminator。
type ProductType string

// PurchaseRequest defines model for PurchaseRequest.
type PurchaseRequest struct {
	// Platform クライアント実行プラットフォーム。
	Platform      Platform `json:"platform"`
	ProductID     string   `json:"product_id"`
	PurchaseToken string   `json:"purchase_token"`
}

// PurchaseResponse defines model for PurchaseResponse.
type PurchaseResponse struct {
	Message   string `json:"message"`
	ProductID string `json:"product_id"`
}

// SubscribeResponse defines model for SubscribeResponse.
type SubscribeResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	Message   string    `json:"message"`
}

// PlayerIdHeader defines model for PlayerIdHeader.
type PlayerIdHeader = string

// ListPlayerProductsParams defines parameters for ListPlayerProducts.
type ListPlayerProductsParams struct {
	// XPlayerId gateway が認証後に付与する player_id。client が直接設定するヘッダではない。
	XPlayerId PlayerIdHeader `json:"X-Player-Id"`
}

// PurchaseProductParams defines parameters for PurchaseProduct.
type PurchaseProductParams struct {
	// XPlayerId gateway が認証後に付与する player_id。client が直接設定するヘッダではない。
	XPlayerId PlayerIdHeader `json:"X-Player-Id"`
}

// SubscribeProductParams defines parameters for SubscribeProduct.
type SubscribeProductParams struct {
	// XPlayerId gateway が認証後に付与する player_id。client が直接設定するヘッダではない。
	XPlayerId PlayerIdHeader `json:"X-Player-Id"`
}

// PurchaseProductJSONRequestBody defines body for PurchaseProduct for application/json ContentType.
type PurchaseProductJSONRequestBody = PurchaseRequest

// SubscribeProductJSONRequestBody defines body for SubscribeProduct for application/json ContentType.
type SubscribeProductJSONRequestBody = PurchaseRequest

// AppleWebhookJSONRequestBody defines body for AppleWebhook for application/json ContentType.
type AppleWebhookJSONRequestBody = AppleNotificationPayload

// GoogleWebhookJSONRequestBody defines body for GoogleWebhook for application/json ContentType.
type GoogleWebhookJSONRequestBody = GoogleRTDNMessage

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListPlayerProducts request
	ListPlayerProducts(ctx context.Context, params *ListPlayerProductsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PurchaseProductWithBody request with any body
	PurchaseProductWithBody(ctx context.Context, params *PurchaseProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PurchaseProduct(ctx context.Context, params *PurchaseProductParams, body PurchaseProductJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubscribeProductWithBody request with any body
	SubscribeProductWithBody(ctx context.Context, params *SubscribeProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SubscribeProduct(ctx context.Context, params *SubscribeProductParams, body SubscribeProductJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AppleWebhookWithBody request with any body
	AppleWebhookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AppleWebhook(ctx context.Context, body AppleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GoogleWebhookWithBody request with any body
	GoogleWebhookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GoogleWebhook(ctx context.Context, body GoogleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListPlayerProducts(ctx context.Context, params *ListPlayerProductsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPlayerProductsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PurchaseProductWithBody(ctx context.Context, params *PurchaseProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPurchaseProductRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PurchaseProduct(ctx context.Context, params *PurchaseProductParams, body PurchaseProductJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPurchaseProductRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubscribeProductWithBody(ctx context.Context, params *SubscribeProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubscribeProductRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubscribeProduct(ctx context.Context, params *SubscribeProductParams, body SubscribeProductJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubscribeProductRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppleWebhookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppleWebhookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppleWebhook(ctx context.Context, body AppleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppleWebhookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GoogleWebhookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGoogleWebhookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GoogleWebhook(ctx context.Context, body GoogleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGoogleWebhookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPlayerProductsRequest generates requests for ListPlayerProducts
func NewListPlayerProductsRequest(server string, params *ListPlayerProductsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/shop/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Player-Id", params.XPlayerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Player-Id", headerParam0)

	}

	return req, nil
}

// NewPurchaseProductRequest calls the generic PurchaseProduct builder with application/json body
func NewPurchaseProductRequest(server string, params *PurchaseProductParams, body PurchaseProductJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPurchaseProductRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPurchaseProductRequestWithBody generates requests for PurchaseProduct with any type of body
func NewPurchaseProductRequestWithBody(server string, params *PurchaseProductParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/shop/purchase")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Player-Id", params.XPlayerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Player-Id", headerParam0)

	}

	return req, nil
}

// NewSubscribeProductRequest calls the generic SubscribeProduct builder with application/json body
func NewSubscribeProductRequest(server string, params *SubscribeProductParams, body SubscribeProductJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubscribeProductRequestWithBody(server, params, "application/json", bodyReader)
}

// NewSubscribeProductRequestWithBody generates requests for SubscribeProduct with any type of body
func NewSubscribeProductRequestWithBody(server string, params *SubscribeProductParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/shop/subscribe")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Player-Id", params.XPlayerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Player-Id", headerParam0)

	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAppleWebhookRequest calls the generic AppleWebhook builder with application/json body
func NewAppleWebhookRequest(server string, body AppleWebhookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAppleWebhookRequestWithBody(server, "application/json", bodyReader)
}

// NewAppleWebhookRequestWithBody generates requests for AppleWebhook with any type of body
func NewAppleWebhookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webhook/apple")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGoogleWebhookRequest calls the generic GoogleWebhook builder with application/json body
func NewGoogleWebhookRequest(server string, body GoogleWebhookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGoogleWebhookRequestWithBody(server, "application/json", bodyReader)
}

// NewGoogleWebhookRequestWithBody generates requests for GoogleWebhook with any type of body
func NewGoogleWebhookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webhook/google")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListPlayerProductsWithResponse request
	ListPlayerProductsWithResponse(ctx context.Context, params *ListPlayerProductsParams, reqEditors ...RequestEditorFn) (*ListPlayerProductsResponse, error)

	// PurchaseProductWithBodyWithResponse request with any body
	PurchaseProductWithBodyWithResponse(ctx context.Context, params *PurchaseProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PurchaseProductResponse, error)

	PurchaseProductWithResponse(ctx context.Context, params *PurchaseProductParams, body PurchaseProductJSONRequestBody, reqEditors ...RequestEditorFn) (*PurchaseProductResponse, error)

	// SubscribeProductWithBodyWithResponse request with any body
	SubscribeProductWithBodyWithResponse(ctx context.Context, params *SubscribeProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubscribeProductResponse, error)

	SubscribeProductWithResponse(ctx context.Context, params *SubscribeProductParams, body SubscribeProductJSONRequestBody, reqEditors ...RequestEditorFn) (*SubscribeProductResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// AppleWebhookWithBodyWithResponse request with any body
	AppleWebhookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppleWebhookResponse, error)

	AppleWebhookWithResponse(ctx context.Context, body AppleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*AppleWebhookResponse, error)

	// GoogleWebhookWithBodyWithResponse request with any body
	GoogleWebhookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GoogleWebhookResponse, error)

	GoogleWebhookWithResponse(ctx context.Context, body GoogleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*GoogleWebhookResponse, error)
}

type ListPlayerProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProductListResponse
}

// Status returns HTTPResponse.Status
func (r ListPlayerProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPlayerProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPlayerProductsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PurchaseProductResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PurchaseResponse
}

// Status returns HTTPResponse.Status
func (r PurchaseProductResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PurchaseProductResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PurchaseProductResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SubscribeProductResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubscribeResponse
}

// Status returns HTTPResponse.Status
func (r SubscribeProductResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubscribeProductResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SubscribeProductResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AppleWebhookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AppleWebhookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AppleWebhookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AppleWebhookResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GoogleWebhookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GoogleWebhookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GoogleWebhookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GoogleWebhookResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListPlayerProductsWithResponse request returning *ListPlayerProductsResponse
func (c *ClientWithResponses) ListPlayerProductsWithResponse(ctx context.Context, params *ListPlayerProductsParams, reqEditors ...RequestEditorFn) (*ListPlayerProductsResponse, error) {
	rsp, err := c.ListPlayerProducts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPlayerProductsResponse(rsp)
}

// PurchaseProductWithBodyWithResponse request with arbitrary body returning *PurchaseProductResponse
func (c *ClientWithResponses) PurchaseProductWithBodyWithResponse(ctx context.Context, params *PurchaseProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PurchaseProductResponse, error) {
	rsp, err := c.PurchaseProductWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePurchaseProductResponse(rsp)
}

func (c *ClientWithResponses) PurchaseProductWithResponse(ctx context.Context, params *PurchaseProductParams, body PurchaseProductJSONRequestBody, reqEditors ...RequestEditorFn) (*PurchaseProductResponse, error) {
	rsp, err := c.PurchaseProduct(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePurchaseProductResponse(rsp)
}

// SubscribeProductWithBodyWithResponse request with arbitrary body returning *SubscribeProductResponse
func (c *ClientWithResponses) SubscribeProductWithBodyWithResponse(ctx context.Context, params *SubscribeProductParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubscribeProductResponse, error) {
	rsp, err := c.SubscribeProductWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubscribeProductResponse(rsp)
}

func (c *ClientWithResponses) SubscribeProductWithResponse(ctx context.Context, params *SubscribeProductParams, body SubscribeProductJSONRequestBody, reqEditors ...RequestEditorFn) (*SubscribeProductResponse, error) {
	rsp, err := c.SubscribeProduct(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubscribeProductResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// AppleWebhookWithBodyWithResponse request with arbitrary body returning *AppleWebhookResponse
func (c *ClientWithResponses) AppleWebhookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppleWebhookResponse, error) {
	rsp, err := c.AppleWebhookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppleWebhookResponse(rsp)
}

func (c *ClientWithResponses) AppleWebhookWithResponse(ctx context.Context, body AppleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*AppleWebhookResponse, error) {
	rsp, err := c.AppleWebhook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppleWebhookResponse(rsp)
}

// GoogleWebhookWithBodyWithResponse request with arbitrary body returning *GoogleWebhookResponse
func (c *ClientWithResponses) GoogleWebhookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GoogleWebhookResponse, error) {
	rsp, err := c.GoogleWebhookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGoogleWebhookResponse(rsp)
}

func (c *ClientWithResponses) GoogleWebhookWithResponse(ctx context.Context, body GoogleWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*GoogleWebhookResponse, error) {
	rsp, err := c.GoogleWebhook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGoogleWebhookResponse(rsp)
}

// ParseListPlayerProductsResponse parses an HTTP response from a ListPlayerProductsWithResponse call
func ParseListPlayerProductsResponse(rsp *http.Response) (*ListPlayerProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPlayerProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePurchaseProductResponse parses an HTTP response from a PurchaseProductWithResponse call
func ParsePurchaseProductResponse(rsp *http.Response) (*PurchaseProductResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PurchaseProductResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PurchaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSubscribeProductResponse parses an HTTP response from a SubscribeProductWithResponse call
func ParseSubscribeProductResponse(rsp *http.Response) (*SubscribeProductResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubscribeProductResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubscribeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAppleWebhookResponse parses an HTTP response from a AppleWebhookWithResponse call
func ParseAppleWebhookResponse(rsp *http.Response) (*AppleWebhookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AppleWebhookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGoogleWebhookResponse parses an HTTP response from a GoogleWebhookWithResponse call
func ParseGoogleWebhookResponse(rsp *http.Response) (*GoogleWebhookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GoogleWebhookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
