// Package apishop provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apishop

import (
	"time"
)

// Defines values for Platform.
const (
	PlatformAndroid Platform = "android"
	PlatformIos     Platform = "ios"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case PlatformAndroid:
		return true
	case PlatformIos:
		return true
	default:
		return false
	}
}

// Defines values for ProductType.
const (
	ProductTypeCardPack     ProductType = "card_pack"
	ProductTypeCosmetic     ProductType = "cosmetic"
	ProductTypeFactionSet   ProductType = "faction_set"
	ProductTypeSubscription ProductType = "subscription"
)

// Valid indicates whether the value is a known member of the ProductType enum.
func (e ProductType) Valid() bool {
	switch e {
	case ProductTypeCardPack:
		return true
	case ProductTypeCosmetic:
		return true
	case ProductTypeFactionSet:
		return true
	case ProductTypeSubscription:
		return true
	default:
		return false
	}
}

// AppleNotificationPayload defines model for AppleNotificationPayload.
type AppleNotificationPayload struct {
	// SignedPayload Apple JWS 署名済みペイロード本体。
	SignedPayload string `json:"signedPayload"`
}

// GoogleRTDNMessage defines model for GoogleRTDNMessage.
type GoogleRTDNMessage struct {
	Message GoogleRTDNMessageBody `json:"message"`
}

// GoogleRTDNMessageBody defines model for GoogleRTDNMessageBody.
type GoogleRTDNMessageBody struct {
	// Data base64 エンコードされた DeveloperNotification 本体。
	Data string `json:"data"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Platform クライアント実行プラットフォーム。
type Platform string

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Products []ProductResponse `json:"products"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	// Content 商品 type ごとに固有の構造を持つ JSON オブジェクト。type=faction_set なら `{faction}`, type=cosmetic なら `{item_type, item_no}`, type=subscription なら `{}`、type=card_pack なら `{card_pack_id}`。
	Content     map[string]interface{} `json:"content"`
	Description *string                `json:"description,omitempty"`
	ImageURL    *string                `json:"image_url,omitempty"`
	IsActive    bool                   `json:"is_active"`
	IsOwned     bool                   `json:"is_owned"`
	Name        string                 `json:"name"`
	Price       int64                  `json:"price"`
	ProductID   string                 `json:"product_id"`

	// Type 商品種別の discriminator。
	Type ProductType `json:"type"`
}

// ProductType 商品種別の discriminator。
type ProductType string

// PurchaseRequest defines model for PurchaseRequest.
type PurchaseRequest struct {
	// Platform クライアント実行プラットフォーム。
	Platform      Platform `json:"platform"`
	ProductID     string   `json:"product_id"`
	PurchaseToken string   `json:"purchase_token"`
}

// PurchaseResponse defines model for PurchaseResponse.
type PurchaseResponse struct {
	Message   string `json:"message"`
	ProductID string `json:"product_id"`
}

// SubscribeResponse defines model for SubscribeResponse.
type SubscribeResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	Message   string    `json:"message"`
}

// PlayerIdHeader defines model for PlayerIdHeader.
type PlayerIdHeader = string

// ListPlayerProductsParams defines parameters for ListPlayerProducts.
type ListPlayerProductsParams struct {
	// XPlayerId gateway が認証後に付与する player_id。client が直接設定するヘッダではない。
	XPlayerId PlayerIdHeader `json:"X-Player-Id"`
}

// PurchaseProductParams defines parameters for PurchaseProduct.
type PurchaseProductParams struct {
	// XPlayerId gateway が認証後に付与する player_id。client が直接設定するヘッダではない。
	XPlayerId PlayerIdHeader `json:"X-Player-Id"`
}

// SubscribeProductParams defines parameters for SubscribeProduct.
type SubscribeProductParams struct {
	// XPlayerId gateway が認証後に付与する player_id。client が直接設定するヘッダではない。
	XPlayerId PlayerIdHeader `json:"X-Player-Id"`
}

// PurchaseProductJSONRequestBody defines body for PurchaseProduct for application/json ContentType.
type PurchaseProductJSONRequestBody = PurchaseRequest

// SubscribeProductJSONRequestBody defines body for SubscribeProduct for application/json ContentType.
type SubscribeProductJSONRequestBody = PurchaseRequest

// AppleWebhookJSONRequestBody defines body for AppleWebhook for application/json ContentType.
type AppleWebhookJSONRequestBody = AppleNotificationPayload

// GoogleWebhookJSONRequestBody defines body for GoogleWebhook for application/json ContentType.
type GoogleWebhookJSONRequestBody = GoogleRTDNMessage
