// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apishop

import (
	"encoding/json"
	"time"
)

// ProductResponse は商品カタログ API のレスポンス要素。
type ProductResponse struct {
	ProductID   string          `json:"product_id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Price       int64           `json:"price"`
	Content     json.RawMessage `json:"content"`
	Description *string         `json:"description,omitempty"`
	ImageURL    *string         `json:"image_url,omitempty"`
	IsActive    bool            `json:"is_active"`
	IsOwned     bool            `json:"is_owned"`
}

// PurchaseRequest は POST /shop/purchase および /shop/subscribe のリクエストボディ。
type PurchaseRequest struct {
	ProductID     string `json:"product_id"`
	Platform      string `json:"platform"`
	PurchaseToken string `json:"purchase_token"`
}

type PurchaseResponse struct {
	Message   string `json:"message"`
	ProductID string `json:"product_id"`
}

type SubscribeResponse struct {
	Message   string    `json:"message"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SelectFactionRequest struct {
	Faction string `json:"faction"`
}

type RegisterRequest struct {
	Username string `json:"username"`
}

// AppleNotificationPayload は Apple が /webhook/apple に送る最上位ボディ。
type AppleNotificationPayload struct {
	SignedPayload string `json:"signedPayload"`
}

// GoogleRTDNMessage は Google が /webhook/google に送る Pub/Sub push ラッパー。
type GoogleRTDNMessage struct {
	Message GoogleRTDNMessageBody `json:"message"`
}

// GoogleRTDNMessageBody は GoogleRTDNMessage の内側の message 封筒。
type GoogleRTDNMessageBody struct {
	Data string `json:"data"`
}

