// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apishop

import (
	"time"
)

const (
	TopicFactionPurchased = "faction-purchased"
	EventTypeFactionPurchased = "faction_purchased"
)

// FactionPurchasedEvent はプレイヤーが faction を購入した際に shop が発行するイベント。
// subscriber: account (player_factions に INSERT) / card (faction 固有カード付与) / gateway (WS 通知)。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type FactionPurchasedEvent struct {
	EventType string    `json:"event_type"`
	EventID   string    `json:"event_id"`
	Timestamp time.Time `json:"timestamp"`
	PlayerID  string    `json:"player_id"`
	Faction   string    `json:"faction"`
}

