// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apishop

import (
	"time"
)

const (
	TopicPremiumUpdated = "premium-updated"
	EventTypePremiumUpdated = "premium_updated"
	PremiumUpdatedSourceShop = "shop"
)

// PremiumUpdatedEvent は subscription 状態遷移により is_premium が変化した際に shop が発行するイベント。
// subscriber: account (players.is_premium / premium_expires_at を更新) / gateway (WS 通知)。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type PremiumUpdatedEvent struct {
	EventType        string     `json:"event_type"`
	EventID          string     `json:"event_id"`
	Timestamp        time.Time  `json:"timestamp"`
	PlayerID         string     `json:"player_id"`
	IsPremium        bool       `json:"is_premium"`
	PremiumExpiresAt *time.Time `json:"premium_expires_at,omitempty"`
	Source           string     `json:"source"`
}

