// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apishop

import (
	"encoding/json"
	"time"
)

const (
	ProductTypeFactionSet = "faction_set"
	ProductTypeCosmetic = "cosmetic"
	ProductTypeSubscription = "subscription"
	PlatformIOS = "ios"
	PlatformAndroid = "android"
	ItemTypeStamp = "stamp"
	ItemTypePlaymat = "playmat"
	ItemTypeSleeve = "sleeve"
	ItemTypeIcon = "icon"
	SubscriptionStatusActive = "active"
	SubscriptionStatusExpired = "expired"
	SubscriptionStatusCancelled = "cancelled"
	SubscriptionStatusGracePeriod = "grace_period"
	SubscriptionStatusRevoked = "revoked"
)

// Product represents a purchasable item in the shop catalog.
type Product struct {
	ProductID   string          `json:"product_id" db:"product_id"`
	Name        string          `json:"name" db:"name"`
	Type        string          `json:"type" db:"type"`
	Price       int64           `json:"price" db:"price"`
	Content     json.RawMessage `json:"content" db:"content"`
	Description *string         `json:"description,omitempty" db:"description"`
	ImageURL    *string         `json:"image_url,omitempty" db:"image_url"`
	IsActive    bool            `json:"is_active" db:"is_active"`
}

type FactionSetContent struct {
	Faction string `json:"faction"`
}

type CosmeticContent struct {
	ItemType string `json:"item_type"`
	ItemNo   int64  `json:"item_no"`
}

type OneTimePurchase struct {
	PurchaseID  int64     `json:"purchase_id" db:"purchase_id"`
	PlayerID    string    `json:"player_id" db:"player_id"`
	ProductID   string    `json:"product_id" db:"product_id"`
	PurchasedAt time.Time `json:"purchased_at" db:"purchased_at"`
}

type Subscription struct {
	SubscriptionID     int64     `json:"subscription_id" db:"subscription_id"`
	PlayerID           string    `json:"player_id" db:"player_id"`
	ProductID          string    `json:"product_id" db:"product_id"`
	Status             string    `json:"status" db:"status"`
	CurrentPeriodStart time.Time `json:"current_period_start" db:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end" db:"current_period_end"`
	CreatedAt          time.Time `json:"created_at" db:"created_at"`
	UpdatedAt          time.Time `json:"updated_at" db:"updated_at"`
}

type AppleSubscriptionToken struct {
	Token          string    `json:"token" db:"token"`
	SubscriptionID int64     `json:"subscription_id" db:"subscription_id"`
	CreatedAt      time.Time `json:"created_at" db:"created_at"`
	UpdatedAt      time.Time `json:"updated_at" db:"updated_at"`
}

type GoogleSubscriptionToken struct {
	Token          string    `json:"token" db:"token"`
	SubscriptionID int64     `json:"subscription_id" db:"subscription_id"`
	CreatedAt      time.Time `json:"created_at" db:"created_at"`
	UpdatedAt      time.Time `json:"updated_at" db:"updated_at"`
}

type ApplePurchaseToken struct {
	Token      string    `json:"token" db:"token"`
	PurchaseID int64     `json:"purchase_id" db:"purchase_id"`
	CreatedAt  time.Time `json:"created_at" db:"created_at"`
}

type GooglePurchaseToken struct {
	Token      string    `json:"token" db:"token"`
	PurchaseID int64     `json:"purchase_id" db:"purchase_id"`
	CreatedAt  time.Time `json:"created_at" db:"created_at"`
}

type CosmeticItem struct {
	ItemType      string  `json:"item_type" db:"item_type"`
	ItemNo        int64   `json:"item_no" db:"item_no"`
	ItemName      string  `json:"item_name" db:"item_name"`
	Description   *string `json:"description,omitempty" db:"description"`
	IsPurchasable bool    `json:"is_purchasable" db:"is_purchasable"`
	IsActive      bool    `json:"is_active" db:"is_active"`
}

type PlayerItem struct {
	PlayerID   string    `json:"player_id" db:"player_id"`
	ItemType   string    `json:"item_type" db:"item_type"`
	ItemNo     int64     `json:"item_no" db:"item_no"`
	AcquiredAt time.Time `json:"acquired_at" db:"acquired_at"`
}

// ProductResponse is the API response element for the shop catalog endpoint.
type ProductResponse struct {
	ProductID   string          `json:"product_id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Price       int64           `json:"price"`
	Content     json.RawMessage `json:"content"`
	Description *string         `json:"description,omitempty"`
	ImageURL    *string         `json:"image_url,omitempty"`
	IsActive    bool            `json:"is_active"`
	IsOwned     bool            `json:"is_owned"`
}

// PurchaseRequest is the request body for POST /shop/purchase and /shop/subscribe.
type PurchaseRequest struct {
	ProductID     string `json:"product_id"`
	Platform      string `json:"platform"`
	PurchaseToken string `json:"purchase_token"`
}

type PurchaseResponse struct {
	Message   string `json:"message"`
	ProductID string `json:"product_id"`
}

type SubscribeResponse struct {
	Message   string    `json:"message"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SelectFactionRequest struct {
	Faction string `json:"faction"`
}

type RegisterRequest struct {
	Username string `json:"username"`
}

// AppleNotificationPayload is the top-level body Apple sends to /webhook/apple.
type AppleNotificationPayload struct {
	SignedPayload string `json:"signedPayload"`
}

// GoogleRTDNMessage is the Pub/Sub push wrapper Google sends to /webhook/google.
type GoogleRTDNMessage struct {
	Message GoogleRTDNMessageBody `json:"message"`
}

// GoogleRTDNMessageBody is the inner message envelope of GoogleRTDNMessage.
type GoogleRTDNMessageBody struct {
	Data string `json:"data"`
}

