/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービス死活監視 (ClusterIP 内部のみ) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 購入可能な商品一覧を返す (所持情報付き) */
        get: operations["listPlayerProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 1 回限りの商品を購入 (faction_set / cosmetic 等) */
        post: operations["purchaseProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** サブスクリプション商品を購入 (プレミアムパス等) */
        post: operations["subscribeProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple App Store Server Notifications V2 を受信
         * @description 認証は Apple JWS 署名検証 (Firebase Auth 不要)。IAP_VERIFIER=stub 時はルーティング自体が登録されない。
         */
        post: operations["appleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Real-Time Developer Notifications を受信
         * @description 認証は Google Pub/Sub push 署名検証 (Firebase Auth 不要)。IAP_VERIFIER=stub 時はルーティング自体が登録されない。
         */
        post: operations["googleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        ProductListResponse: {
            products: components["schemas"]["ProductResponse"][];
        };
        ProductResponse: {
            product_id: string;
            name: string;
            type: components["schemas"]["ProductType"];
            /** Format: int64 */
            price: number;
            /** @description 商品 type ごとに固有の構造を持つ JSON オブジェクト。type=faction_set なら `{faction}`, type=cosmetic なら `{item_type, item_no}`, type=subscription なら `{}`、type=card_pack なら `{card_pack_id}`。 */
            content: {
                [key: string]: unknown;
            };
            description?: string;
            image_url?: string;
            is_active: boolean;
            is_owned: boolean;
        };
        PurchaseRequest: {
            product_id: string;
            platform: components["schemas"]["Platform"];
            purchase_token: string;
        };
        PurchaseResponse: {
            /** @example purchase accepted */
            message: string;
            product_id: string;
        };
        SubscribeResponse: {
            /** @example subscription accepted */
            message: string;
            /** Format: date-time */
            expires_at: string;
        };
        AppleNotificationPayload: {
            /** @description Apple JWS 署名済みペイロード本体。 */
            signedPayload: string;
        };
        GoogleRTDNMessage: {
            message: components["schemas"]["GoogleRTDNMessageBody"];
        };
        GoogleRTDNMessageBody: {
            /** @description base64 エンコードされた DeveloperNotification 本体。 */
            data: string;
        };
        /**
         * @description クライアント実行プラットフォーム。
         * @enum {string}
         */
        Platform: "ios" | "android";
        /**
         * @description 商品種別の discriminator。
         * @enum {string}
         */
        ProductType: "faction_set" | "card_pack" | "cosmetic" | "subscription";
    };
    responses: never;
    parameters: {
        /** @description gateway が認証後に付与する player_id。client が直接設定するヘッダではない。 */
        PlayerIdHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listPlayerProducts: {
        parameters: {
            query?: never;
            header: {
                /** @description gateway が認証後に付与する player_id。client が直接設定するヘッダではない。 */
                "X-Player-Id": components["parameters"]["PlayerIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 商品一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description X-Player-Id header が欠落 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    purchaseProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description gateway が認証後に付与する player_id。client が直接設定するヘッダではない。 */
                "X-Player-Id": components["parameters"]["PlayerIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description 購入成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"];
                };
            };
            /** @description 無効なファクション / 非アクティブ商品 / 非対応プラットフォーム */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description X-Player-Id header が欠落 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description レシート検証失敗 */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 商品が見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 同一商品を既に所有 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subscribeProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description gateway が認証後に付与する player_id。client が直接設定するヘッダではない。 */
                "X-Player-Id": components["parameters"]["PlayerIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description サブスク登録成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscribeResponse"];
                };
            };
            /** @description 商品がサブスクリプションタイプでない / 非対応プラットフォーム */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description X-Player-Id header が欠落 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description サブスクリプション検証失敗 */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 商品が見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    appleWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppleNotificationPayload"];
            };
        };
        responses: {
            /** @description 通知受領 (空 body) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON パースエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 通知処理失敗 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleRTDNMessage"];
            };
        };
        responses: {
            /** @description 通知受領 (空 body) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON パースエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 通知処理失敗 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
