-- Code generated by scripts/generate_products_seed.py; DO NOT EDIT.

INSERT INTO shop.products (product_id, name, type, price, description, image_url, is_active) VALUES ('faction_set_she', 'SHE Pack', 'faction_set', 980, 'SHE 陣営のカードセット', NULL, TRUE);
INSERT INTO shop.product_faction (product_id, faction) VALUES ('faction_set_she', 'SHE');
INSERT INTO shop.product_card_pack (product_id, card_pack_id) VALUES ('faction_set_she', 'faction_set_she');

INSERT INTO shop.products (product_id, name, type, price, description, image_url, is_active) VALUES ('faction_set_tenki', 'Tenki Pack', 'faction_set', 980, '天気使い陣営のカードセット', NULL, TRUE);
INSERT INTO shop.product_faction (product_id, faction) VALUES ('faction_set_tenki', 'Tenki');
INSERT INTO shop.product_card_pack (product_id, card_pack_id) VALUES ('faction_set_tenki', 'faction_set_tenki');

INSERT INTO shop.products (product_id, name, type, price, description, image_url, is_active) VALUES ('faction_set_sugar', 'Sugar Pack', 'faction_set', 980, 'しゅがーらぼ陣営のカードセット', NULL, TRUE);
INSERT INTO shop.product_faction (product_id, faction) VALUES ('faction_set_sugar', 'Sugar');
INSERT INTO shop.product_card_pack (product_id, card_pack_id) VALUES ('faction_set_sugar', 'faction_set_sugar');

INSERT INTO shop.products (product_id, name, type, price, description, image_url, is_active) VALUES ('faction_set_tuners', 'Tuners Pack', 'faction_set', 980, '調律部陣営のカードセット', NULL, TRUE);
INSERT INTO shop.product_faction (product_id, faction) VALUES ('faction_set_tuners', 'Tuners');
INSERT INTO shop.product_card_pack (product_id, card_pack_id) VALUES ('faction_set_tuners', 'faction_set_tuners');
