-- Auto-generated by scripts/generate_products_seed.py. DO NOT EDIT.

INSERT INTO shop.products (product_id, name, type, price, description, image_url, is_active)
VALUES
  ('faction_set_she', 'SHE Pack', 'faction_set', 980, 'SHE 陣営のカードセット', NULL, true),
  ('faction_set_tenki', 'Tenki Pack', 'faction_set', 980, '天気使い陣営のカードセット', NULL, true),
  ('faction_set_sugar', 'Sugar Pack', 'faction_set', 980, 'しゅがーらぼ陣営のカードセット', NULL, true),
  ('faction_set_tuners', 'Tuners Pack', 'faction_set', 980, '調律部陣営のカードセット', NULL, true)
ON CONFLICT (product_id) DO UPDATE SET
  name        = EXCLUDED.name,
  type        = EXCLUDED.type,
  price       = EXCLUDED.price,
  description = EXCLUDED.description,
  image_url   = EXCLUDED.image_url,
  is_active   = EXCLUDED.is_active;

INSERT INTO shop.product_faction (product_id, faction)
VALUES
  ('faction_set_she', 'SHE'),
  ('faction_set_tenki', 'Tenki'),
  ('faction_set_sugar', 'Sugar'),
  ('faction_set_tuners', 'Tuners')
ON CONFLICT (product_id) DO UPDATE SET
  faction = EXCLUDED.faction;

INSERT INTO shop.product_card_pack (product_id, card_pack_id)
VALUES
  ('faction_set_she', 'faction_set_she'),
  ('faction_set_tenki', 'faction_set_tenki'),
  ('faction_set_sugar', 'faction_set_sugar'),
  ('faction_set_tuners', 'faction_set_tuners')
ON CONFLICT (product_id) DO UPDATE SET
  card_pack_id = EXCLUDED.card_pack_id;
