#!/usr/bin/env python3
"""data/products.yaml から db/seed/products_seed.sql を生成する。

shop.products と型別副表 (shop.product_faction / shop.product_card_pack /
shop.product_cosmetic / shop.product_subscription) への INSERT を
1 ファイルにまとめて出力する。

使い方:
    python3 scripts/generate_products_seed.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "products.yaml"
OUT = ROOT / "db" / "seed" / "products_seed.sql"
GENERATED_HEADER = "-- Code generated by scripts/generate_products_seed.py; DO NOT EDIT.\n\n"

# 型別の必須付帯フィールド (本副表 INSERT の組み立てに使う)。
TYPE_REQUIRED_FIELDS = {
    "faction_set": ("faction", "card_pack_id"),
    "card_pack": ("card_pack_id",),
}


def _sql_str(v: str) -> str:
    """SQL 文字列リテラルにエスケープして埋め込む."""
    return "'" + v.replace("'", "''") + "'"


def _sql_optional_str(v):
    """NULL 許容文字列。値が None なら NULL を出す."""
    return "NULL" if v is None else _sql_str(v)


def _validate(products):
    """products リストを構造的に検証する."""
    seen_ids = set()
    for i, p in enumerate(products):
        loc = f"products[{i}]"
        for key in ("product_id", "name", "type", "price", "is_active"):
            if key not in p:
                raise ValueError(f"{loc}: missing required key {key!r}")
        if p["product_id"] in seen_ids:
            raise ValueError(f"{loc}: duplicate product_id {p['product_id']!r}")
        seen_ids.add(p["product_id"])
        required = TYPE_REQUIRED_FIELDS.get(p["type"])
        if required is None:
            raise ValueError(
                f"{loc}: unsupported type {p['type']!r}. "
                f"supported: {sorted(TYPE_REQUIRED_FIELDS)}"
            )
        for key in required:
            if key not in p:
                raise ValueError(
                    f"{loc}: type={p['type']!r} requires {key!r}"
                )


def _emit_product(p) -> list[str]:
    """1 商品分の INSERT 文 (本表 + 型別副表) を返す."""
    lines = []
    lines.append(
        "INSERT INTO shop.products "
        "(product_id, name, type, price, description, image_url, is_active) "
        f"VALUES ({_sql_str(p['product_id'])}, {_sql_str(p['name'])}, "
        f"{_sql_str(p['type'])}, {p['price']}, "
        f"{_sql_optional_str(p.get('description'))}, "
        f"{_sql_optional_str(p.get('image_url'))}, "
        f"{'TRUE' if p['is_active'] else 'FALSE'});"
    )
    if p["type"] == "faction_set":
        lines.append(
            "INSERT INTO shop.product_faction (product_id, faction) "
            f"VALUES ({_sql_str(p['product_id'])}, {_sql_str(p['faction'])});"
        )
        lines.append(
            "INSERT INTO shop.product_card_pack (product_id, card_pack_id) "
            f"VALUES ({_sql_str(p['product_id'])}, {_sql_str(p['card_pack_id'])});"
        )
    elif p["type"] == "card_pack":
        lines.append(
            "INSERT INTO shop.product_card_pack (product_id, card_pack_id) "
            f"VALUES ({_sql_str(p['product_id'])}, {_sql_str(p['card_pack_id'])});"
        )
    return lines


def generate(src_path: Path = SRC, out_path: Path = OUT) -> None:
    """YAML を読み SQL を書き出す."""
    data = yaml.safe_load(src_path.read_text(encoding="utf-8"))
    products = data.get("products") or []
    _validate(products)

    out_lines = [GENERATED_HEADER.rstrip("\n")]
    for p in products:
        out_lines.append("")
        out_lines.extend(_emit_product(p))
    out_lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines), encoding="utf-8")


def main() -> int:
    """エントリポイント."""
    generate()
    print(f"Generated → {OUT.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
