#!/usr/bin/env python3
"""
Codegen for overload-party-shop.

Reads data/models.yaml (SSoT for shop-owned types) and emits:
  - packages/api-shop/*_gen.go       (Go module, package apishop)

Run:  python3 scripts/generate_types.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.stderr.write("error: PyYAML is required (pip install pyyaml)\n")
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_YAML = REPO_ROOT / "data" / "models.yaml"

# Go
GO_PACKAGE_DIR = REPO_ROOT / "packages" / "api-shop"
GO_PACKAGE_NAME = "apishop"

GENERATED_HEADER_GO = "// Code generated by scripts/generate_types.py; DO NOT EDIT."

# ─── Go helpers ────────────────────────────────────────────


def _go_type_needs_import(type_str: str) -> set[str]:
    imports: set[str] = set()
    if "time.Time" in type_str or "time." in type_str:
        imports.add("time")
    if "json.RawMessage" in type_str:
        imports.add("encoding/json")
    if "civil.Date" in type_str or "civil." in type_str:
        imports.add("cloud.google.com/go/civil")
    return imports


def _emit_go_import_block(imports: set[str]) -> list[str]:
    if not imports:
        return []
    std = sorted(i for i in imports if "." not in i.split("/")[0])
    ext = sorted(i for i in imports if "." in i.split("/")[0])
    lines = ["import ("]
    for imp in std:
        lines.append(f'\t"{imp}"')
    if std and ext:
        lines.append("")
    for imp in ext:
        lines.append(f'\t"{imp}"')
    lines.append(")")
    lines.append("")
    return lines


def _emit_go_constants(constants: list[dict]) -> list[str]:
    lines: list[str] = []
    for const_block in constants:
        const_type = const_block.get("type", "string")
        values = const_block.get("values", [])
        if not values:
            continue
        lines.append("const (")
        for v in values:
            name = v["name"]
            value = v["value"]
            if const_type == "string":
                lines.append(f'\t{name} = "{value}"')
            else:
                lines.append(f"\t{name} = {value}")
        lines.append(")")
        lines.append("")
    return lines


def _emit_go_type(td: dict) -> list[str]:
    lines: list[str] = []
    if td.get("comment"):
        lines.append(f"// {td['comment']}")
    lines.append(f"type {td['name']} struct {{")

    fields = td.get("fields", [])
    if fields:
        max_name_len = max(len(f["name"]) for f in fields)
        max_type_len = max(len(str(f["type"])) for f in fields)

    for field in fields:
        fname = field["name"]
        ftype = str(field["type"])
        tags: list[str] = []
        if "json" in field:
            tags.append(f'json:"{field["json"]}"')
        if "db" in field:
            tags.append(f'db:"{field["db"]}"')
        tag_str = " ".join(tags)

        name_pad = " " * (max_name_len - len(fname) + 1)
        type_pad = " " * (max_type_len - len(ftype) + 1)

        if tag_str:
            line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_str}`"
        else:
            line = f"\t{fname}{name_pad}{ftype}"

        if field.get("comment"):
            line += f" // {field['comment']}"
        lines.append(line)

    lines.append("}")
    lines.append("")
    return lines


def _generate_go_file(file_def: dict) -> None:
    lines: list[str] = [GENERATED_HEADER_GO, "", f"package {GO_PACKAGE_NAME}", ""]

    imports = set(file_def.get("imports", []))
    for td in file_def.get("types", []):
        for field in td.get("fields", []):
            imports |= _go_type_needs_import(str(field["type"]))

    lines.extend(_emit_go_import_block(imports))

    # constants
    constants = file_def.get("constants", [])
    lines.extend(_emit_go_constants(constants))

    # types
    for td in file_def.get("types", []):
        lines.extend(_emit_go_type(td))

    out_path = GO_PACKAGE_DIR / f"{file_def['name']}_gen.go"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


# ─── Main ─────────────────────────────────────────────────


def main() -> int:
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    sections = data.get("files")
    if not sections:
        sys.stderr.write("error: data/models.yaml has no `files:` section\n")
        return 1

    # Go models
    for file_def in sections:
        _generate_go_file(file_def)

    return 0


if __name__ == "__main__":
    sys.exit(main())
