#!/usr/bin/env python3
"""Generate shop product seed SQL from data/products.yaml.

Outputs:
  - db/seed/products_seed.sql  (PostgreSQL UPSERT seed for shop.products と
                                 型別副表 shop.product_faction /
                                 shop.product_card_pack)

Usage:
    python3 scripts/generate_products_seed.py

`data/products.yaml` is the SSoT. The output SQL is regenerated each run and
must not be edited by hand. Re-applying the seed is idempotent
(ON CONFLICT DO UPDATE); 副表は 1:1 関係なので product_id 単独で UPSERT する。
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
YAML_IN = ROOT / "data" / "products.yaml"
SEED_OUT = ROOT / "db" / "seed" / "products_seed.sql"

# 型別の必須付帯フィールド (本副表 INSERT の組み立てに使う)。
TYPE_REQUIRED_FIELDS = {
    "faction_set": ("faction", "card_pack_id"),
    "card_pack": ("card_pack_id",),
}


def load_products() -> list[dict]:
    """data/products.yaml を読み products リストを返す."""
    with YAML_IN.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "products" not in data:
        raise ValueError(f"{YAML_IN}: top-level 'products' key is required")
    return data["products"] or []


def validate(products: list[dict]) -> None:
    """products リストを構造的に検証する."""
    seen_ids: set[str] = set()
    for i, p in enumerate(products):
        loc = f"products[{i}]"
        for key in ("product_id", "name", "type", "price", "is_active"):
            if key not in p:
                raise ValueError(f"{loc}: missing required key {key!r}")
        pid = p["product_id"]
        if pid in seen_ids:
            raise ValueError(f"{loc}: duplicate product_id {pid!r}")
        seen_ids.add(pid)
        required = TYPE_REQUIRED_FIELDS.get(p["type"])
        if required is None:
            raise ValueError(
                f"{loc}: unsupported type {p['type']!r}. "
                f"supported: {sorted(TYPE_REQUIRED_FIELDS)}"
            )
        for key in required:
            if key not in p:
                raise ValueError(f"{loc}: type={p['type']!r} requires {key!r}")


def sql_quote(s: str) -> str:
    """SQL 文字列リテラルにエスケープ."""
    return "'" + s.replace("'", "''") + "'"


def sql_optional(v) -> str:
    """NULL 許容文字列。None で NULL を出す."""
    return "NULL" if v is None else sql_quote(v)


def render_seed(products: list[dict]) -> str:
    """products から PostgreSQL UPSERT SQL 全文を組み立てる."""
    lines = ["-- Auto-generated by scripts/generate_products_seed.py. DO NOT EDIT.", ""]

    product_rows = []
    faction_rows = []
    card_pack_rows = []
    for p in products:
        pid = sql_quote(p["product_id"])
        product_rows.append(
            f"  ({pid}, {sql_quote(p['name'])}, {sql_quote(p['type'])}, "
            f"{p['price']}, {sql_optional(p.get('description'))}, "
            f"{sql_optional(p.get('image_url'))}, "
            f"{'true' if p['is_active'] else 'false'})"
        )
        if p["type"] == "faction_set":
            faction_rows.append(f"  ({pid}, {sql_quote(p['faction'])})")
            card_pack_rows.append(f"  ({pid}, {sql_quote(p['card_pack_id'])})")
        elif p["type"] == "card_pack":
            card_pack_rows.append(f"  ({pid}, {sql_quote(p['card_pack_id'])})")

    lines.append("INSERT INTO shop.products (product_id, name, type, price, description, image_url, is_active)")
    lines.append("VALUES")
    lines.append(",\n".join(product_rows))
    lines.append("ON CONFLICT (product_id) DO UPDATE SET")
    lines.append("  name        = EXCLUDED.name,")
    lines.append("  type        = EXCLUDED.type,")
    lines.append("  price       = EXCLUDED.price,")
    lines.append("  description = EXCLUDED.description,")
    lines.append("  image_url   = EXCLUDED.image_url,")
    lines.append("  is_active   = EXCLUDED.is_active;")
    lines.append("")

    if faction_rows:
        lines.append("INSERT INTO shop.product_faction (product_id, faction)")
        lines.append("VALUES")
        lines.append(",\n".join(faction_rows))
        lines.append("ON CONFLICT (product_id) DO UPDATE SET")
        lines.append("  faction = EXCLUDED.faction;")
        lines.append("")

    if card_pack_rows:
        lines.append("INSERT INTO shop.product_card_pack (product_id, card_pack_id)")
        lines.append("VALUES")
        lines.append(",\n".join(card_pack_rows))
        lines.append("ON CONFLICT (product_id) DO UPDATE SET")
        lines.append("  card_pack_id = EXCLUDED.card_pack_id;")
        lines.append("")

    return "\n".join(lines)


def generate(src_path: Path = YAML_IN, out_path: Path = SEED_OUT) -> None:
    """YAML を読み SQL を書き出す."""
    with src_path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "products" not in data:
        raise ValueError(f"{src_path}: top-level 'products' key is required")
    products = data["products"] or []
    validate(products)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_seed(products), encoding="utf-8")


def main() -> int:
    """エントリポイント."""
    generate()
    print(f"Generated → {SEED_OUT.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
