// Code generated by scripts/generate_types.py; DO NOT EDIT.

package domain

import (
	"time"
)

const (
	TopicFactionAcquired = "faction-acquired"
	EventTypeFactionAcquired = "faction_acquired"
)

// FactionAcquiredEvent はプレイヤーが faction を獲得した業務事実を表す shop 発行イベント。
// subscriber: account (player_factions に INSERT、authoritative 所有権) / gateway (WS 一次通知)。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type FactionAcquiredEvent struct {
	EventType string    `json:"event_type"`
	EventID   string    `json:"event_id"`
	Timestamp time.Time `json:"timestamp"`
	PlayerID  string    `json:"player_id"`
	Faction   string    `json:"faction"`
}

