// Code generated by scripts/generate_types.py; DO NOT EDIT.

package domain

import (
	"time"
)

const (
	TopicCardPackPurchased = "card-pack-purchased"
	EventTypeCardPackPurchased = "card_pack_purchased"
)

// CardPackPurchasedEvent はプレイヤーが card_pack を含む商品 (faction_set / card_pack 等) を購入した際に shop が発行するイベント。
// subscriber: card (GrantPack(card_pack_id) でカード配布) / gateway (WS 副次通知)。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type CardPackPurchasedEvent struct {
	EventType  string    `json:"event_type"`
	EventID    string    `json:"event_id"`
	Timestamp  time.Time `json:"timestamp"`
	PlayerID   string    `json:"player_id"`
	CardPackID string    `json:"card_pack_id"`
}

