// Code generated by scripts/generate_types.py; DO NOT EDIT.

package domain

import (
	"time"
)

// Product は shop カタログの購入可能商品の共通属性。type 固有属性は FactionSetProduct / CosmeticProduct / SubscriptionProduct 等の per-type 型が保持する。
type Product struct {
	ProductID   string
	Name        string
	Type        string
	Price       int64
	Description *string
	ImageURL    *string
	IsActive    bool
}

// FactionSetProduct は ProductTypeFactionSet の per-type ビュー。Product 共通属性 + faction 配布対象を保持する。
type FactionSetProduct struct {
	Product Product
	Faction string
}

// CosmeticProduct は ProductTypeCosmetic の per-type ビュー。Product 共通属性 + cosmetic_items への参照を保持する。
type CosmeticProduct struct {
	Product  Product
	ItemType string
	ItemNo   int64
}

// SubscriptionProduct は ProductTypeSubscription の per-type ビュー。Product 共通属性 + 課金周期 (月数) を保持する。
type SubscriptionProduct struct {
	Product      Product
	PeriodMonths int64
}

// OneTimePurchase は単発 (非サブスクリプション) の購入レコード。
type OneTimePurchase struct {
	PurchaseID  int64
	PlayerID    string
	ProductID   string
	PurchasedAt time.Time
}

// Subscription は継続課金の権利レコード。
type Subscription struct {
	SubscriptionID     int64
	PlayerID           string
	ProductID          string
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// PlayerItem はプレイヤーが所有する cosmetic アイテム。
type PlayerItem struct {
	PlayerID   string
	ItemType   string
	ItemNo     int64
	AcquiredAt time.Time
}

// ProductWithOwnership は per-type ProductView (FactionSetProduct / CosmeticProduct / SubscriptionProduct のいずれか) にリクエスト元プレイヤーの所有状態を付与した usecase 層のビュー。
type ProductWithOwnership struct {
	ProductView ProductView
	IsOwned     bool
}

