// Code generated by scripts/generate_types.py; DO NOT EDIT.

package domain

import (
	"encoding/json"
	"time"
)

// Product は shop カタログの購入可能商品。
type Product struct {
	ProductID   string
	Name        string
	Type        string
	Price       int64
	Content     json.RawMessage
	Description *string
	ImageURL    *string
	IsActive    bool
}

// FactionSetContent は ProductTypeFactionSet の Product.Content を parse した結果。
type FactionSetContent struct {
	Faction string `json:"faction"`
}

// CosmeticContent は ProductTypeCosmetic の Product.Content を parse した結果。
type CosmeticContent struct {
	ItemType string `json:"item_type"`
	ItemNo   int64  `json:"item_no"`
}

// OneTimePurchase は単発 (非サブスクリプション) の購入レコード。
type OneTimePurchase struct {
	PurchaseID  int64
	PlayerID    string
	ProductID   string
	PurchasedAt time.Time
}

// Subscription は継続課金の権利レコード。
type Subscription struct {
	SubscriptionID     int64
	PlayerID           string
	ProductID          string
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// PlayerItem はプレイヤーが所有する cosmetic アイテム。
type PlayerItem struct {
	PlayerID   string
	ItemType   string
	ItemNo     int64
	AcquiredAt time.Time
}

// ProductWithOwnership は Product にリクエスト元プレイヤーの所有状態を付与した usecase 層のビュー。
type ProductWithOwnership struct {
	Product Product
	IsOwned bool
}

