// Code generated by scripts/generate_types.py; DO NOT EDIT.

package domain

const (
	ProductTypeFactionSet = "faction_set"
	ProductTypeCardPack = "card_pack"
	ProductTypeCosmetic = "cosmetic"
	ProductTypeSubscription = "subscription"
	PlatformIOS = "ios"
	PlatformAndroid = "android"
	ItemTypeStamp = "stamp"
	ItemTypePlaymat = "playmat"
	ItemTypeSleeve = "sleeve"
	ItemTypeIcon = "icon"
	SubscriptionStatusActive = "active"
	SubscriptionStatusExpired = "expired"
	SubscriptionStatusCancelled = "cancelled"
	SubscriptionStatusGracePeriod = "grace_period"
	SubscriptionStatusRevoked = "revoked"
)

